blog/urls.py
from django.urls import path
from . import views 


app_name = 'blog'

urlpatterns = [
    path('', views.allBlogs, name="allBlogs"),
    path('<int:blog_id>/', views.detail, name="detail"),

]

personalPortfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="home"),
    path('blog/', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.
class Blog(models.Model):
	blogTitle = models.CharField(max_length=200)
	datePosted = models.DateField(auto_now=False, auto_now_add=False)
	blogContent = models.TextField()
	
	def __str_(self):
		return self.title

portfolio/models.py
from django.db import models

# Create your models here.
class Project(models.Model):
	title = models.CharField(max_length=100)
	description = models.CharField(max_length=250)
	image = models.ImageField(upload_to='portfolio/images/')
	url = models.URLField(blank=True)

#returns default name in admin for an object
	def __str_(self):
		return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog

# Create your views here.
def allBlogs(request):
	blogs = Blog.objects.all()
	return render(request, 'blog/allBlogs.html', {'blogs':blogs} )

def detail(request, blog_id):
	blog = get_object_or_404(Blog, pk=blog_id)
	return render(request, 'blog/detail.html', {'blog':blog})

portfolio/views.py
from django.shortcuts import render
from .models import Project

# Create your views here.
def home(request):
	projects = Project.objects.all()
	return render(request, 'portfolio/home.html', {'projects':projects})

blog/templates/blog/allBlogs.html
{% extends 'portfolio/basePage.html'%}


{% block content%}
<h1 id="blogtitle" class="font-weight-bold text-center"> Tevani's Bloggity Blog </h1>


<h3 class="text-center m-5"> We got bout {{blogs.count}} post{{blogs.count|pluralize}}!</h3>


{%for i in blogs%}


<div class="row justify-content-center my-3">

  <div class="col-md-10">
	<a href = "{% url 'blog:detail' i.id %}">
		<h3>{{i.blogTitle}}</h3>
	</a>

	<h6 class="text-muted">{{i.datePosted|date:'M d Y'|upper}}</h6>

	<h4>{{i.blogContent|truncatechars:100}}</h4>
	
	</div>
</div>

{%endfor%}

{% endblock%}

blog/templates/blog/detail.html
{% extends "portfolio/basePage.html" %}

{% load static %}

{% block content %}

<h1 class="text-center mt-5" id="blogdetailtitle">{{ blog.blogTitle }}</h1>

<h5 class="text-center text-muted mb-5">{{ blog.datePosted|date:'F jS Y' }}</h5>

{{ blog.blogContent|safe }}

{% endblock %}

portfolio/templates/portfolio/basePage.html
{%load static%}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static "portfolio/custom.css" %}">

    <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">

     <link rel="icon" type="image/png" href="{% static "portfolio/Logo.png" %}">

    <title>Tevizzle</title>
  </head>
  <body>
    <nav id="topNav" class="navbar navbar-expand-md navbar-dark ">
    <div class="container">
      <a class="navbar-brand" href="{% url 'home' %}">
        <img src="{% static "portfolio/Logo.png" %}" width="30" height="30" class="d-inline-block align-top" alt="a pink flower">
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse text-center" id="navbarNav">                              
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% static "portfolio/resume.pdf" %}">Resume</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://www.linkedin.com/in/tevani-hibbert/" target="_blank">LinkedIn</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://repl.it/@tevanihibbert" target="_blank">Repl.it</a>
          </li>
          <li>
            <a role="button" href="{% url 'blog:allBlogs' %}" class="btn btn-primary">Blog</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <br>
  <div class="container">
    {% block content %}{% endblock %}
  </div>








    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

    
  </body>
</html>

portfolio/templates/portfolio/home.html
{% extends 'portfolio/basePage.html' %}

{% block content %}

{%load static%}


<div class="row justify-content-center my-3">
  <div class="col-5">
    <img src="{% static 'portfolio/winnie.jpg' %}" class="img-fluid">
  </div>
</div>


<div class="row justify-content-center mb-3">
  <div class="col-md-9 text-center">
    <h1 id="hometext" class="font-weight-bold m-4" >Hi, I'm Tevani and i'm pretty cool 🧍🏾‍♀️ </h1>
  </div>
</div>


<h2 class="mt-5">Portfolio</h2>
<hr>


<div class="row">

{%for i in projects%}
  	<div class="col-lg-4 col-md-6">

		{%if i.url%}

			<a href="{{i.url}}"> 
			<img src= '{{i.image.url}}' class="img-fluid mb-2">
			 </a>

		{% else %}

			<img src= '{{i.image.url}}' class="img-fluid mb-2">
	
		{%endif%}

	<h3>{{ i.title }}</h3>
    <p>{{ i.description }}</p>

 	</div>

{% endfor %}

</div>

  

{%endblock%}